### ISSUE TITLE
InvalidClientIdError: (invalid_request) Missing required parameter: refresh_token

### ISSUE THREAD

**Issue by kevinhughes27** [singingwolfboy/flask-dance#137]
I get the following error after a while with my Google Provider. I'm not sure if its the Flask session or the Google Access token expiring. I'll dig deeper but wanted to open the issue now in case anyone else has seen this before.

```
* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2018-06-16 12:27:45,324] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 48, in decorated_function
    resp = google.get("/oauth2/v2/userinfo")
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_dance/consumer/requests.py", line 141, in request
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 343, in request
    self.auto_refresh_url, auth=auth, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 415, in raise_from_error
    raise cls(**kwargs)
InvalidClientIdError: (invalid_request) Missing required parameter: refresh_token
```

**Comment by singingwolfboy** [comment]
Hmm, it appears that the code tried to automatically refresh your expired OAuth token, but it wasn't able to do so successfully. I'm not sure if the problem is with Flask-Dance, Requests-OAuthlib, or the way your OAuth connection is set up. Do you have `offline=True` set in the Google blueprint factory?

**Comment by kevinhughes27** [comment]
It occurred to me later after digging into something else that the issue may be with one of those other libraries. I do not have `offline=True` set on the blueprint. I can try adding it and see what happens.

**Comment by kevinhughes27** [comment]
`offline=True` crashes with `RefreshError: ('invalid_grant: Invalid JWT Signature.', u'{\n  "error" : "invalid_grant",\n  "error_description" : "Invalid JWT Signature."\n}')`.

Its probably not an issue with flask-dance so feel free to close.

**Comment by singingwolfboy** [comment]
@kevinhughes27, did you ever find the solution to your problem? If so, can you add a comment explaining what you did? Other people may find this GitHub issue in the future, and want to know what the solution was.
