### ISSUE TITLE
Need to provide "offline_access" mode for Azure

### ISSUE THREAD

**Issue by dev-johnlopez** [singingwolfboy/flask-dance#176]
I added the offline_access scope item as discussed [in this article. (search on offline_access)](https://docs.microsoft.com/en-us/outlook/rest/python-tutorial). I'm looking into your codebase to figure out exactly where the error is occurring.

Here is the output after I logged in with it:

```
2018-10-02T01:53:17.127911+00:00 app[web.1]: [2018-10-02 01:53:17 +0000] [24] [ERROR] Error handling request /login/azure/authorized?code=<redacted>&state=<redacted>
2018-10-02T01:53:17.127928+00:00 app[web.1]: Traceback (most recent call last):
2018-10-02T01:53:17.127930+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
2018-10-02T01:53:17.127931+00:00 app[web.1]: self.handle_request(listener, req, client, addr)
2018-10-02T01:53:17.127932+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
2018-10-02T01:53:17.127934+00:00 app[web.1]: respiter = self.wsgi(environ, resp.start_response)
2018-10-02T01:53:17.127935+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
2018-10-02T01:53:17.127937+00:00 app[web.1]: return self.wsgi_app(environ, start_response)
2018-10-02T01:53:17.127938+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
2018-10-02T01:53:17.127939+00:00 app[web.1]: return self.app(environ, start_response)
2018-10-02T01:53:17.127941+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
2018-10-02T01:53:17.127942+00:00 app[web.1]: response = self.handle_exception(e)
2018-10-02T01:53:17.127943+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
2018-10-02T01:53:17.127944+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2018-10-02T01:53:17.127946+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
2018-10-02T01:53:17.127947+00:00 app[web.1]: response = self.full_dispatch_request()
2018-10-02T01:53:17.127948+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
2018-10-02T01:53:17.127949+00:00 app[web.1]: rv = self.handle_user_exception(e)
2018-10-02T01:53:17.127951+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
2018-10-02T01:53:17.127952+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2018-10-02T01:53:17.127953+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
2018-10-02T01:53:17.127954+00:00 app[web.1]: rv = self.dispatch_request()
2018-10-02T01:53:17.127955+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
2018-10-02T01:53:17.127957+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2018-10-02T01:53:17.127958+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/flask_dance/consumer/oauth2.py", line 246, in authorized
2018-10-02T01:53:17.127960+00:00 app[web.1]: **self.token_url_params
2018-10-02T01:53:17.127961+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
2018-10-02T01:53:17.127962+00:00 app[web.1]: self._client.parse_request_body_response(r.text, scope=self.scope)
2018-10-02T01:53:17.127964+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
2018-10-02T01:53:17.127965+00:00 app[web.1]: self.token = parse_token_response(body, scope=scope)
2018-10-02T01:53:17.127966+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
2018-10-02T01:53:17.127967+00:00 app[web.1]: validate_token_parameters(params)
2018-10-02T01:53:17.127968+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 409, in validate_token_parameters
2018-10-02T01:53:17.127970+00:00 app[web.1]: raise w
2018-10-02T01:53:17.127971+00:00 app[web.1]: Warning: Scope has changed from "profile email offline_access openid User.Read" to "email profile openid User.Read".
2018-10-02T01:53:17.128169+00:00 app[web.1]: 10.61.181.115 - - [02/Oct/2018:01:53:17 +0000] "GET /login/azure/authorized?code=<redacted>&state<redacted>HTTP/1.1" 500 0 "-" "-"
```

**Comment by dev-johnlopez** [comment]
Mistake on my end.

Documentation should be updated to include setting OAUTHLIB_RELAX_TOKEN_SCOPE=1 if offline_access is required. This documentation is in the google provider documentation but should probably be in all documentation.
