### ISSUE TITLE
SqlAlchemy storage example - RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by RichardCullen** [singingwolfboy/flask-dance#264]
Trying the example code in https://flask-dance.readthedocs.io/en/latest/storages.html#sqlalchemy-storage, the app won't start:

```
<snip>
from flask_sqlalchemy import SQLAlchemy
from flask_dance.consumer.storage.sqla import SQLAlchemyStorage, OAuthConsumerMixin
<snip>

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///tmp/test.db'
db = SQLAlchemy(app)

class OAuth(OAuthConsumerMixin, db.Model):
    pass
<snip>
cognito.storage = SQLAlchemyStorage(OAuth,db.session,user=current_user)
app.register_blueprint(cognito_bp, url_prefix="/login")
```

```
Traceback (most recent call last):
  File "cognito.py", line 58, in <module>
    cognito.storage = SQLAlchemyStorage(OAuth,db.session,user=current_user)
  File "C:\work\python\okta-flask-example\env\lib\site-packages\werkzeug\local.py", line 364, in <lambda>
    __setattr__ = lambda x, n, v: setattr(x._get_current_object(), n, v)
  File "C:\work\python\okta-flask-example\env\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\globals.py", line 44, in _lookup_app_object
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
```

**Comment by daenney** [comment]
Isn't is supposed to be `cognito_bp.storage`? It doesn't jive with the next line where you're referring to it as `cognito_bp` in `register_blueprint`.

**Comment by RichardCullen** [comment]
🤦‍♂  Thanks for spotting the typo...!
