### ISSUE TITLE
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

### ISSUE THREAD

**Issue by macmule** [singingwolfboy/flask-dance#318]
We receive the below error web trying to save who changed an item in our views.py, however this seems to be only in prod.

In dev running on kubernetes locally, all is well.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_admin/model/base.py", line 2143, in edit_view
    if self.update_model(form, model):
  File "/usr/local/lib/python3.6/dist-packages/flask_admin/contrib/sqla/view.py", line 1160, in update_model
    if not self.handle_view_exception(ex):
  File "/usr/local/lib/python3.6/dist-packages/flask_admin/contrib/sqla/view.py", line 1112, in handle_view_exception
    return super(ModelView, self).handle_view_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/flask_admin/contrib/sqla/view.py", line 1157, in update_model
    self._on_model_change(form, model, False)
  File "/usr/local/lib/python3.6/dist-packages/flask_admin/model/base.py", line 1570, in _on_model_change
    self.on_model_change(form, model, is_created)
  File "/usr/local/envQUERY/views.py", line 312, in on_model_change
    okta_response = okta_blueprint.session.get('{}/userinfo'.format(ISSUER_URL))
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_dance/consumer/requests.py", line 201, in request
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/requests_oauthlib/oauth2_session.py", line 478, in request
    url, http_method=method, body=data, headers=headers
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 
```

Trimmed down views.py:

```import datetime
from flask import (Flask,
                   redirect,
                   url_for)
from flask_admin.contrib.sqla import ModelView
from flask_dance.consumer import OAuth2ConsumerBlueprint

app = Flask(__name__, instance_relative_config=True)
app.config.from_object('config.Config')

ISSUER_URL = '{}/v1'.format(app.config['OKTA_ISSUER_URL'])
okta_blueprint = OAuth2ConsumerBlueprint(
    'okta', __name__,
    client_id=app.config['OKTA_CLIENT_ID'],
    client_secret=app.config['OKTA_CLIENT_SECRET'],
    token_url='{}/token'.format(ISSUER_URL),
    authorization_url='{}/authorize'.format(ISSUER_URL),
    scope=['openid', 'profile', 'email'],
    url_prefix='/login'
)

#pylint: disable=too-few-public-methods
class RepositoryView(ModelView):
    ''' Settings for the details view '''

    # redacted

    @classmethod
    def on_model_change(cls, _, model, is_created):
        ''' If details changed, submit who changed them & remove whitespace'''

        app.logger.debug(" --- RepositoryView: on_model_change --- ")

        if not okta_blueprint.authorized:
            return redirect(url_for("okta.login"))

        okta_response = okta_blueprint.session.get('{}/userinfo'.format(ISSUER_URL))

        app.logger.debug(okta_response)
        okta_email = okta_response.json()['email']
        app.logger.debug(okta_email)

        if is_created is True:
            app.logger.debug('repository record created')
            app.logger.debug("okta_response: %s" % okta_response)
            app.logger.debug("okta_email: %s" % okta_email)
            model.created_by = okta_email
            model.created_time = datetime.datetime.utcnow().replace(microsecond=0)
        else:
            app.logger.debug('repository record modified')
            app.logger.debug("okta_response: %s" % okta_response)
            app.logger.debug("okta_email: %s" % okta_email)
            model.modified_by = okta_email
            model.modified_time = datetime.datetime.utcnow().replace(microsecond=0)

        model.customer_id = model.customer_id.strip().lower()
        app.logger.debug("model.customer_id: %s" % model.customer_id)
        app.logger.debug("model: %s" % model)
```

In dev we're accessing the flask app via the same IP flask is setup on, so 0.0.0.0 but we're on a different port with kubernetes sorting that out.

In prod we're connecting via DNS name, could this be the issue?

**Comment by macmule** [comment]
```
  File "/usr/local/envQUERY/views.py", line 312, in on_model_change
    okta_response = okta_blueprint.session.get('{}/userinfo'.format(ISSUER_URL))
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_dance/consumer/requests.py", line 201, in request
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/requests_oauthlib/oauth2_session.py", line 478, in request
    url, http_method=method, body=data, headers=headers
```

So, indeed might be related to the URL somewhere

**Comment by macmule** [comment]
I think the issue was that request wasn't imported from flask, so the url wasn't being passed.

The difference between dev & prod I'm not sure on, but now seems ok in both...

**Comment by macmule** [comment]
So this has come back.

Seems to be due to changing between VPN etc.

The service we're looking to auth to is behind VPN, others are not.

Dunno if that tracks.

Alternatively I'll look to plonk the needed data into the session to grab (it's the users username)

**Comment by singingwolfboy** [comment]
@macmule This issue sounds like it's very specific to your production deployment. If you would like to hire me as a contractor to help you figure out your specific problem, I'm happy to do so: my contact information is on my GitHub profile. However, since this issue seems to be more about your deployment than about Flask-Dance itself, I'm closing this issue.

**Comment by macmule** [comment]
Thanks i was hopeful with https://github.com/singingwolfboy/flask-dance/issues/286#issuecomment-590128910 & simplifying things.

Sadly no luck there either.

Seems that Okta isn't that simple.

I had this app working fine with LDAP & it's behind VPN, so will revert.
